In [1]:
# # Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
from google.colab import files
Uploaded=files.upload()

Saving main.csv to main.csv


In [5]:
dataset= pd.read_csv('main.csv')
print(dataset)

     Gender  Glucose    BP  SkinThickness  ...   BMI  PedigreeFunction  Age  Outcome
0      Male      148  72.0           35.0  ...  33.6             0.627   50        1
1    Female       85  66.0           29.0  ...  26.6             0.351   31        0
2    Female      183  64.0            0.0  ...  23.3             0.672   32        1
3    Female       89  66.0           23.0  ...  28.1             0.167   21        0
4      Male      137   NaN           35.0  ...  43.1             2.288   33        1
..      ...      ...   ...            ...  ...   ...               ...  ...      ...
559    Male       85  74.0            0.0  ...  30.1             0.300   35        0
560    Male      125  76.0            0.0  ...  33.8             0.121   54        1
561    Male      198  66.0           32.0  ...  41.3             0.502   28        1
562    Male       87  68.0           34.0  ...  37.6             0.401   24        0
563    Male       99  60.0           19.0  ...  26.9             

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564 entries, 0 to 563
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Gender            564 non-null    object 
 1   Glucose           564 non-null    int64  
 2   BP                548 non-null    float64
 3   SkinThickness     553 non-null    float64
 4   Insulin           552 non-null    float64
 5   BMI               547 non-null    float64
 6   PedigreeFunction  546 non-null    float64
 7   Age               564 non-null    int64  
 8   Outcome           564 non-null    int64  
dtypes: float64(5), int64(3), object(1)
memory usage: 39.8+ KB


In [8]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:,0:7].values
# Extracting dependent variable:
y = dataset.iloc[:,8].values


In [9]:
#Check Missing Data
dataset.isnull().sum()

Gender               0
Glucose              0
BP                  16
SkinThickness       11
Insulin             12
BMI                 17
PedigreeFunction    18
Age                  0
Outcome              0
dtype: int64

In [10]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, 2:6]) 
#Replacing missing data with the calculated mean value  
X[:, 2:6]= imputer.transform(X[:, 2:6])

In [12]:
#Check Missing Data
dataset.isnull().sum()

Gender               0
Glucose              0
BP                  16
SkinThickness       11
Insulin             12
BMI                 17
PedigreeFunction    18
Age                  0
Outcome              0
dtype: int64

In [13]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, 2:6]) 
#Replacing missing data with the calculated mean value  
X[:, 2:6]= imputer.transform(X[:, 2:6])

In [14]:
#Check Missing Data
dataset.isnull().sum()

Gender               0
Glucose              0
BP                  16
SkinThickness       11
Insulin             12
BMI                 17
PedigreeFunction    18
Age                  0
Outcome              0
dtype: int64

In [15]:
dataset = dataset.dropna()
dataset

Gender  Glucose    BP  SkinThickness  ...   BMI  PedigreeFunction  Age  Outcome
0      Male      148  72.0           35.0  ...  33.6             0.627   50        1
1    Female       85  66.0           29.0  ...  26.6             0.351   31        0
2    Female      183  64.0            0.0  ...  23.3             0.672   32        1
3    Female       89  66.0           23.0  ...  28.1             0.167   21        0
5    Female      116  74.0            0.0  ...  25.6             0.201   30        0
..      ...      ...   ...            ...  ...   ...               ...  ...      ...
559    Male       85  74.0            0.0  ...  30.1             0.300   35        0
560    Male      125  76.0            0.0  ...  33.8             0.121   54        1
561    Male      198  66.0           32.0  ...  41.3             0.502   28        1
562    Male       87  68.0           34.0  ...  37.6             0.401   24        0
563    Male       99  60.0           19.0  ...  26.9             0.497   32        0

[497 rows x 9 columns]

In [16]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, 2:6]) 
#Replacing missing data with the calculated mean value  
X[:, 2:6]= imputer.transform(X[:, 2:6])

In [17]:
#Check Missing Data
dataset.isnull().sum()

Gender              0
Glucose             0
BP                  0
SkinThickness       0
Insulin             0
BMI                 0
PedigreeFunction    0
Age                 0
Outcome             0
dtype: int64

In [18]:

from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])


In [19]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 497 entries, 0 to 563
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Gender            497 non-null    object 
 1   Glucose           497 non-null    int64  
 2   BP                497 non-null    float64
 3   SkinThickness     497 non-null    float64
 4   Insulin           497 non-null    float64
 5   BMI               497 non-null    float64
 6   PedigreeFunction  497 non-null    float64
 7   Age               497 non-null    int64  
 8   Outcome           497 non-null    int64  
dtypes: float64(5), int64(3), object(1)
memory usage: 38.8+ KB


In [20]:
print(X)

[[1 148 72.0 ... 0.0 33.6 0.627]
 [0 85 66.0 ... 0.0 26.6 0.35100000000000003]
 [0 183 64.0 ... 0.0 23.3 0.672]
 ...
 [1 198 66.0 ... 274.0 41.3 0.502]
 [1 87 68.0 ... 77.0 37.6 0.401]
 [1 99 60.0 ... 54.0 26.9 0.49700000000000005]]


In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)

In [22]:
print(X_train)

[[1 171 110.0 ... 240.0 45.4 0.721]
 [0 106 52.0 ... 0.0 31.2 0.38]
 [1 161 68.76824817518248 ... 0.0 31.8308957952468 0.165]
 ...
 [1 95 64.0 ... 0.0 32.0 0.161]
 [0 97 60.0 ... 0.0 28.2 0.44299999999999995]
 [1 196 76.0 ... 280.0 37.5 0.605]]


In [23]:
print(X_test)

[[1 170 64.0 37.0 225.0 34.5 0.35600000000000004]
 [1 105 68.76824817518248 32.0 68.0 30.8 0.122]
 [1 128 78.0 0.0 0.0 21.1 0.268]
 [1 133 88.0 15.0 155.0 32.4 0.262]
 [1 142 86.0 0.0 0.0 44.0 0.645]
 [1 95 82.0 25.0 180.0 35.0 nan]
 [0 124 74.0 0.0 0.0 34.0 0.22]
 [1 83 65.0 28.0 66.0 36.8 0.629]
 [0 144 82.0 26.0 285.0 32.0 0.452]
 [0 99 52.0 15.0 94.0 24.6 0.637]
 [0 155 62.0 26.0 495.0 34.0 nan]
 [0 90 70.0 17.0 0.0 27.3 0.085]
 [0 176 90.0 34.0 300.0 33.7 0.467]
 [1 96 64.0 27.0 87.0 33.2 0.289]
 [0 132 80.0 0.0 0.0 26.8 0.18600000000000003]
 [0 189 64.0 20.61844484629295 325.0 31.2 0.583]
 [1 175 62.0 30.0 0.0 33.6 0.212]
 [1 87 68.0 34.0 77.0 37.6 0.401]
 [0 145 82.0 19.0 110.0 22.2 0.245]
 [1 107 88.0 0.0 0.0 36.8 0.727]
 [1 119 0.0 0.0 0.0 19.6 0.8320000000000001]
 [1 88 78.0 30.0 0.0 27.6 0.258]
 [1 180 64.0 25.0 70.0 34.0 0.271]
 [1 128 48.0 45.0 194.0 40.5 0.613]
 [1 144 58.0 28.0 140.0 29.5 0.287]
 [1 135 94.0 46.0 145.0 40.6 0.284]
 [0 152 88.0 44.0 0.0 50.0 0.337]
 [0 11

In [24]:
print(y_train)

[1 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0
 0 0 0 1 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 0 1 0 1 1 1 0
 1 1 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 1 1 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0
 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 0 1 0 0 1 0 1 0 0 0 1 0 0 1
 1 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1
 0 1 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 0 1 1 1 0 1 1 1 0 0 1 1
 0 1 1 0 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 1 1 1 0 0 0 1 0 1 0 0 0 1 0 1 0 1 0
 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1]


In [25]:
print(y_test)

[1 0 0 0 1 1 1 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 0
 1 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0
 0 1 1 1 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 1 1]


In [27]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [28]:
print(X_train)

[[ 9.29212636e-01  1.63216202e+00  2.18741024e+00 ...  1.45737721e+00
   1.65886194e+00  6.55276556e-01]
 [-1.07617994e+00 -4.12316101e-01 -8.90915735e-01 ... -6.74235800e-01
  -7.59901505e-02 -3.13601637e-01]
 [ 9.29212636e-01  1.31762693e+00 -9.47907652e-04 ... -6.74235800e-01
   1.08808090e-03 -9.24477917e-01]
 ...
 [ 9.29212636e-01 -7.58304707e-01 -2.54020705e-01 ... -6.74235800e-01
   2.17479951e-02 -9.35843058e-01]
 [-1.07617994e+00 -6.95397687e-01 -4.66319048e-01 ... -6.74235800e-01
  -4.42508197e-01 -1.34600681e-01]
 [ 9.29212636e-01  2.41849976e+00  3.82874325e-01 ...  1.81264604e+00
   6.93697747e-01  3.25687493e-01]]


In [29]:
print(X_test)

[[ 9.29212636e-01  1.60070851e+00 -2.54020705e-01  1.06638842e+00
   1.32415140e+00  3.27179700e-01 -3.81792478e-01]
 [ 9.29212636e-01 -4.43769611e-01 -9.47907652e-04  7.46882149e-01
  -7.02787807e-02 -1.24859223e-01 -1.04665317e+00]
 [ 9.29212636e-01  2.79661110e-01  4.89023497e-01 -1.29795797e+00
  -6.74235800e-01 -1.30993424e+00 -6.31825560e-01]
 [ 9.29212636e-01  4.36928658e-01  1.01976936e+00 -3.39439163e-01
   7.02430935e-01  7.06170680e-02 -6.48873270e-01]
 [ 9.29212636e-01  7.20010245e-01  9.13620183e-01 -1.29795797e+00
  -6.74235800e-01  1.48782018e+00  4.39338894e-01]
 [ 9.29212636e-01 -7.58304707e-01  7.01321840e-01  2.99573374e-01
   9.24473957e-01  3.88266041e-01             nan]
 [-1.07617994e+00  1.53847072e-01  2.76725154e-01 -1.29795797e+00
  -6.74235800e-01  2.66093359e-01 -7.68207241e-01]
 [ 9.29212636e-01 -1.13574682e+00 -2.00946119e-01  4.91277135e-01
  -8.80422225e-02  6.08176869e-01  3.93878334e-01]
 [-1.07617994e+00  7.82917264e-01  7.01321840e-01  3.63474627e-0

In [31]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, 2:6]) 
#Replacing missing data with the calculated mean value  
X[:, 2:6]= imputer.transform(X[:, 2:6])

In [32]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:,0:7].values
# Extracting dependent variable:
y = dataset.iloc[:,8].values


In [33]:

from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [34]:
print(X)

[[1 148 72.0 ... 0.0 33.6 0.627]
 [0 85 66.0 ... 0.0 26.6 0.35100000000000003]
 [0 183 64.0 ... 0.0 23.3 0.672]
 ...
 [1 198 66.0 ... 274.0 41.3 0.502]
 [1 87 68.0 ... 77.0 37.6 0.401]
 [1 99 60.0 ... 54.0 26.9 0.49700000000000005]]


In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)

In [36]:

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [38]:
# Predicting the Test set results
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0])

In [39]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[71 12]
 [18 24]]


In [40]:
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 82/100

from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 76.00


In [41]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# calculate precision
# Precision = TruePositives / (TruePositives + FalsePositives) 
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 23/30
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.2f' % (precision))

Precision: 0.67


In [42]:
# calculate recall
# Recall = TruePositives / (TruePositives + FalseNegatives)
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 23/23+11
recall = recall_score(y_test, y_pred, average='macro')
print('Recall: %.3f' % (recall))

Recall: 0.713


In [43]:
# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# (2*0.829*0.906)/0.829+0.906
# calculate score
score = f1_score(y_test, y_pred, average='macro')
print('F-Measure: %.3f' % (score*100))

F-Measure: 72.048


In [45]:
# save the model to disk
import joblib
filename = '/content/drive/My Drive/endterm_model.sav'
joblib.dump(model, filename)
 
# some time later...
 
# load the model from disk
randomforest_model = joblib.load(filename)
result = randomforest_model.score(X_test, y_test)
print(result)

0.76


In [46]:
import pickle 
print("[INFO] Saving model...")
# Save the trained model as a pickle string. 
saved_model=pickle.dump(model,open('/content/drive/My Drive/endterm_model.pkl', 'wb')) 
# Saving model to disk

[INFO] Saving model...


In [47]:
# Load the pickled model 
model = pickle.load(open('/content/drive/My Drive/endterm_model.pkl', 'rb'))  
# Use the loaded pickled model to make predictions 
model.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0])

In [68]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [49]:
!pip install streamlit

     |████████████████████████████████| 7.8MB 5.1MB/s 
     |████████████████████████████████| 4.2MB 37.8MB/s 
     |████████████████████████████████| 112kB 35.0MB/s 
     |████████████████████████████████| 81kB 8.3MB/s 
     |████████████████████████████████| 174kB 40.4MB/s 
     |████████████████████████████████| 122kB 40.9MB/s 
     |████████████████████████████████| 71kB 8.0MB/s 
  Created wheel for blinker: filename=blinker-1.4-cp37-none-any.whl size=13476 sha256=565f290eb07a132bf1845cf70c82008d9e37b06ea76658906c9e97e1e64d45ac
  Stored in directory: /root/.cache/pip/wheels/92/a0/00/8690a57883956a301d91cf4ec999cc0b258b01e3f548f86e89
Successfully built blinker
ERROR: ipykernel 6.0.2 has requirement ipython<8.0,>=7.23.1, but you'll have ipython 5.5.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement ipykernel~=4.10, but you'll have ipykernel 6.0.2 which is incompatible.
  Found existing installation: importlib-metadata 4.6.1
    Uninstalling importlib-metadata-4.6.1:
 

In [50]:
!pip install pyngrok

     |████████████████████████████████| 747kB 6.5MB/s 
  Created wheel for pyngrok: filename=pyngrok-5.0.5-cp37-none-any.whl size=19262 sha256=2bea967479ae5b1752dafa3b49f59526112f042a2d37fa558ff3fb20834986d8
  Stored in directory: /root/.cache/pip/wheels/0c/13/64/5ebbcc22eaf53fdf5766b397c1fb17c83f5775fdccf0ea1b88
Successfully built pyngrok


In [69]:
!ngrok authtoken 1rh7vlXXZxc7RJ8rPFV1UzSbAdN_49pPNkGSrCEHw2GdRsNJp|

/bin/bash: -c: line 1: syntax error: unexpected end of file


In [119]:
%%writefile app.py
import streamlit as st 
from PIL import Image
import pickle
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
st.set_option('deprecation.showfileUploaderEncoding', False)
# Load the pickled model
model = pickle.load(open('/content/drive/My Drive/endterm_model.pkl', 'rb')) 
# Feature Scaling
dataset = pd.read_csv('/content/drive/My Drive/main.csv')
# Extracting independent variable:
X = dataset.iloc[:, [1,2,3,4,5,6,7]].values
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

def predict_note_authentication(Gender,Glucose,BP,SkinThickness, Insulin, BMI , PedigreeFunction):
  output= model.predict([[Gender,Glucose,BP,SkinThickness, Insulin, BMI , PedigreeFunction]])
  print("heartdisease", output)
  if output==[0]:
    prediction="No Heartdisease"
  else :
    prediction="Heartdisease"
  
  print(prediction)
  return prediction
def main():
    
    html_temp = """
   <div class="" style="background-color:Brown;" >
   <div class="clearfix">           
   <div class="col-md-12">
   <center><p style="font-size:40px;color:black;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center> 
   <center><p style="font-size:30px;color:black;margin-top:10px;">Department of Computer Engineering</p></center> 
   <center><p style="font-size:25px;color:black;margin-top:10px;"Machine Learning Endterm lab Experiment</p></center> 
   </div>
   </div>
   </div>
   """
    st.markdown(html_temp,unsafe_allow_html=True)
    st.header("Heartdisease Predictor")

    Gender = st.number_input('Insert a Gender',0,1)
    Glucose= st.number_input('Insert a 1-4 ')
    BP=st.number_input('Insert a BP reading ')
    SkinThickness = st.number_input('Insert between 100 - 200 ')
    Insulin = st.number_input('Insert between 100 - 400 ')
    BMI = st.number_input('Insert 0 or 1 ')
    PedigreeFunction = st.number_input('Insert  ')

    
   
    resul=""
    if st.button("Predict"):
      result=predict_note_authentication(Gender,Glucose,BP,SkinThickness, Insulin, BMI , PedigreeFunction)
      st.success('Model has predicted {}'.format(result))
      
    if st.button("About"):
      st.subheader("Developed by Prakhar Mehrishi")
      st.subheader("Head , Department of Computer Engineering")

if __name__=='__main__':
  main()

Overwriting app.py


In [124]:
!nohup streamlit run  app.py &

nohup: appending output to 'nohup.out'


In [125]:
from pyngrok import ngrok
url=ngrok.connect(port='8050')
url

<NgrokTunnel: "http://b625f3e09052.ngrok.io" -> "http://localhost:80">

In [126]:
!streamlit run --server.port 80 app.py


  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.2:80
  External URL: http://35.223.158.127:80

heartdisease [0]
No Heartdisease
  Stopping...
